image: node:latest

except:
  changes:
    - package.json
    - CHANGELOG.md

stages:
  - release
  - deploy

create-release:
  stage: release

  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN

  script:
    - yarn install
    - npx semantic-release
