image: node:latest

stages:
  - release
  - deploy
only:
  refs:
    - chezmoi

create-release:
  stage: release

  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN

  script:
    - yarn install
    - npx semantic-release
