image: node:latest

stages:
  - release
  - deploy

create-release:
  stage: release

  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN

  script:
    - yarn install
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_TAG_MESSAGE =~ /#ci-skip#/ || ($CI_COMMIT_TAG == null && $CI_COMMIT_MESSAGE =~ /#ci-skip#/)
      when: never
